name: Deploy to Vercel

on:
  push:
    branches:
      - main  # Change this to your default branch name if it's different

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'  # Ensure this matches your project's node version

    - name: Install dependencies
      run: npm install

    - name: Generate Prisma Client
      run: npm run postinstall

    - name: Build the project
      run: npm run build

    - name: Deploy to Vercel
      run: npx vercel --prod --token ${{ secrets.VERCEL_TOKEN }}
      env:
        VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
        VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
